# Generated by Django 5.1.5 on 2026-05-11 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_applicationstagelog_interviewpreparation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICareerCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_goals', models.TextField(blank=True)),
                ('current_level', models.CharField(blank=True, max_length=50)),
                ('target_level', models.CharField(blank=True, max_length=50)),
                ('recommended_roles', models.JSONField(blank=True, default=list)),
                ('skill_development_plan', models.JSONField(blank=True, default=list)),
                ('career_milestones', models.JSONField(blank=True, default=list)),
                ('personalized_advice', models.TextField(blank=True)),
                ('job_recommendations', models.JSONField(blank=True, default=list)),
                ('salary_insights', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_coach', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveIntegerField(default=0)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('detailed_feedback', models.TextField(blank=True)),
                ('readability_score', models.PositiveIntegerField(default=0)),
                ('impact_score', models.PositiveIntegerField(default=0)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='jobs.resume')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_jobs', models.JSONField(blank=True, default=list)),
                ('saved_candidates', models.JSONField(blank=True, default=list)),
                ('pipeline_stages', models.JSONField(blank=True, default=dict)),
                ('hiring_goals', models.JSONField(blank=True, default=dict)),
                ('interview_schedule', models.JSONField(blank=True, default=list)),
                ('team_members', models.JSONField(blank=True, default=list)),
                ('notifications_settings', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIMatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.PositiveIntegerField(default=0)),
                ('skills_alignment', models.PositiveIntegerField(default=0)),
                ('experience_alignment', models.PositiveIntegerField(default=0)),
                ('culture_fit', models.PositiveIntegerField(default=0)),
                ('growth_potential', models.PositiveIntegerField(default=0)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('bonus_skills', models.JSONField(blank=True, default=list)),
                ('match_reasons', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_matches', to='jobs.jobpost')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_matches', to='jobs.resume')),
            ],
            options={
                'ordering': ['-match_percentage'],
                'unique_together': {('job', 'resume')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient'], name='jobs_chatme_sender__d28ee1_idx'), models.Index(fields=['recipient', 'is_read'], name='jobs_chatme_recipie_903a14_idx')],
            },
        ),
    ]
