# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_externaljoblisting_otpverification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaljoblisting",
            name="source",
            field=models.CharField(
                choices=[
                    ("jsearch", "JSearch API"),
                    ("adzuna", "Adzuna API"),
                    ("remotive", "Remotive API"),
                    ("google_jobs", "Google Jobs"),
                    ("linkedin", "LinkedIn-style Jobs"),
                ],
                max_length=20,
            ),
        ),
    ]
