# Generated by Django 5.1.5 on 2026-05-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_externaljoblisting_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
