# Generated by Django 5.1.5 on 2026-05-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_companyprofile_companyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='candidate_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
    ]
