# Generated by Django 5.1.5 on 2026-05-12 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_subscriptionplan_usersubscription_usageledger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeJobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.FloatField(default=0.0)),
                ('required_skills_match', models.FloatField(default=0.0)),
                ('nice_to_have_match', models.FloatField(default=0.0)),
                ('experience_multiplier', models.FloatField(default=1.0)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills_required', models.JSONField(blank=True, default=list)),
                ('missing_skills_nice', models.JSONField(blank=True, default=list)),
                ('extracted_resume_skills', models.JSONField(blank=True, default=list)),
                ('extracted_job_skills', models.JSONField(blank=True, default=list)),
                ('candidate_experience_years', models.PositiveIntegerField(default=0)),
                ('required_experience_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior')], default='mid', max_length=20)),
                ('experience_gap', models.IntegerField(default=0)),
                ('match_breakdown', models.JSONField(blank=True, default=dict)),
                ('improvement_suggestions', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-match_percentage', '-analyzed_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='usageledger',
            name='jobs_usagel_user_id_33127b_idx',
        ),
        migrations.AddField(
            model_name='resumejobmatch',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_matches', to='jobs.jobpost'),
        ),
        migrations.AddField(
            model_name='resumejobmatch',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='jobs.resume'),
        ),
        migrations.AddIndex(
            model_name='resumejobmatch',
            index=models.Index(fields=['resume', '-match_percentage'], name='jobs_resume_resume__982539_idx'),
        ),
        migrations.AddIndex(
            model_name='resumejobmatch',
            index=models.Index(fields=['job', '-match_percentage'], name='jobs_resume_job_id_f4755c_idx'),
        ),
        migrations.AddIndex(
            model_name='resumejobmatch',
            index=models.Index(fields=['-analyzed_at'], name='jobs_resume_analyze_4f4dd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resumejobmatch',
            unique_together={('resume', 'job')},
        ),
    ]
