# Generated by Django 5.1.5 on 2026-05-14 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_skillverificationbadge_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, unique=True)),
                ('skill_category', models.CharField(blank=True, max_length=50)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('proficiency_levels', models.JSONField(blank=True, default=list)),
                ('market_weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['skill_category', 'skill_name'],
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='required_certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='required_education',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='required_experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_years',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='parsed_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resumeatsscore',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_score_detail', to='jobs.resume'),
        ),
        migrations.CreateModel(
            name='ResumeJobComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.FloatField(default=0)),
                ('semantic_similarity', models.FloatField(default=0)),
                ('tfidf_similarity', models.FloatField(default=0)),
                ('skill_match', models.JSONField(blank=True, default=dict)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('missing_certifications', models.JSONField(blank=True, default=list)),
                ('experience_score', models.FloatField(default=0)),
                ('ats_score', models.PositiveIntegerField(default=0)),
                ('salary_prediction', models.FloatField(default=0)),
                ('improvement_suggestions', models.JSONField(blank=True, default=list)),
                ('career_recommendations', models.JSONField(blank=True, default=list)),
                ('keyword_analysis', models.JSONField(blank=True, default=dict)),
                ('heatmap', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('comparison_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_comparisons', to='jobs.jobpost')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='jobs.resume')),
            ],
            options={
                'ordering': ['-comparison_date'],
                'indexes': [models.Index(fields=['resume', '-match_percentage'], name='jobs_resume_resume__114587_idx'), models.Index(fields=['job', '-match_percentage'], name='jobs_resume_job_id_88d8df_idx'), models.Index(fields=['status', '-comparison_date'], name='jobs_resume_status_904e10_idx')],
                'unique_together': {('resume', 'job')},
            },
        ),
    ]
