# Generated by Django 5.1.5 on 2026-05-14 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_skillmapping_jobpost_required_certifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('level', models.PositiveSmallIntegerField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Expert')], default=1)),
                ('description', models.TextField(blank=True)),
                ('market_demand', models.FloatField(default=1.0)),
                ('avg_salary', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareerPathModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('typical_years_experience', models.PositiveIntegerField(default=3)),
                ('average_salary_min', models.PositiveIntegerField(default=0)),
                ('average_salary_max', models.PositiveIntegerField(default=0)),
                ('market_demand_score', models.FloatField(default=1.0)),
                ('growth_trajectory', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('optional_skills', models.ManyToManyField(blank=True, related_name='optional_in_paths', to='jobs.skillnode')),
                ('required_skills', models.ManyToManyField(related_name='career_paths', to='jobs.skillnode')),
            ],
            options={
                'ordering': ['-market_demand_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserCareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_completion_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='jobs.careerpathmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_career_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_jump', models.FloatField(default=0.5)),
                ('typical_weeks', models.PositiveIntegerField(default=4)),
                ('is_critical', models.BooleanField(default=False)),
                ('from_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_for', to='jobs.skillnode')),
                ('to_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='jobs.skillnode')),
            ],
            options={
                'ordering': ['typical_weeks'],
                'unique_together': {('from_skill', 'to_skill')},
            },
        ),
        migrations.CreateModel(
            name='UserSkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.PositiveSmallIntegerField(default=1)),
                ('target_level', models.PositiveSmallIntegerField(default=2)),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('learning_resources', models.JSONField(blank=True, default=list)),
                ('milestones_completed', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='jobs.skillnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-progress_percentage'],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
