# Generated by Django 5.1.5 on 2026-05-15 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_features_4_to_10'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queryresult',
            unique_together={('query', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='usageledger',
            index=models.Index(fields=['user', 'usage_type', 'created_at'], name='jobs_usagel_user_id_33127b_idx'),
        ),
    ]
